version: 1.0.{build}-{branch}

image: Visual Studio 2017
init:
  - cmd: git config --global core.autocrlf true
environment:
  github_token:
    secure: W5UODHqSQqiQPupFKXxkM2A5c4i8evVO3kSKV+SikHLYMR8n9ZvWJZqquZFA6aXp

  azure_pwd1:
    secure: 7PmlZ5iEcSExpD6y1++gzHmQJeLSzuSxUk6upBi1BD7x1iev16BlkB/7ZN65buOv87Rr9M5v60l18UUo5D140A==
  azure_pwd2:
    secure: OQuOhjB3wU4zkGpqkQ8JjUOeHHv0Q2z4T2M8Bdd4CN6LZtee37L/8MA5+A6I6URLjoouYF4h7ccKKGKwhKxQvg==
    
install:
  - nuget restore
  
  
build:
  project: WebAppTestDeployment.sln
  publish_wap: true

deploy:
- provider: WebDeploy
  password: $(azure_pwd1)
  website: WebAppTestDeployment
  username: $WebAppTestDeployment
  server: https://webapptestdeployment.scm.azurewebsites.net:443/msdeploy.axd?site=WebAppTestDeployment
  NTLM: disabled
  on: 
    branch: Master
  
- provider: WebDeploy
  password: $(azure_pwd2)
  website: WebAppTestDeployment2
  username: $WebAppTestDeployment2
  server: https://webapptestdeployment2.scm.azurewebsites.net:443/msdeploy.axd?site=WebAppTestDeployment2
  NTLM: disabled
  on:
    branch: Staging

on_success:
  - ps: md C:/Projects/wiki
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:github_token):x-oauth-basic@github.com`n"
  - git config --global user.email "owenmcdonnell@appveyor.com"
  - git config --global user.name "OwenMcdonnell"
  - cd C:/Projects/wiki
  - git clone --branch=master "https://github.com/OwenMcDonnell/netcoreConsoleApp.wiki.git" -q
  - cd netcoreConsoleApp.wiki
  - git status
  - ps: Add-content "Home.md" "added content"
  - git status
  - git add .
  - git status
  - git commit -m "Commiting changes"
  - git status
  - git push
  - git status

